name: Contributor Leaderboard

on:
  workflow_dispatch:
  push:

jobs:
  leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # IMPORTANT: ensures full history

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install GitPython

      - name: Generate Leaderboard
        run: python .github/scripts/generate_leaderboard.py

      - name: Upload Leaderboard
        uses: actions/upload-artifact@v4
        with:
          name: leaderboard
          path: leaderboard.json
