name: Build & Release - .NET 8 WPF (Self-Contained EXE)

on:
  push:
    tags:
      - 'v*'   # Triggers on tags like v1.0.0, v1.1.3 etc.

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: DesktopStacksService.sln
      Project_Path: DesktopStacksService.csproj

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore NuGet packages
        run: dotnet restore ${{ env.Solution_Name }}

      - name: Publish self-contained EXE
        run: >
          dotnet publish ${{ env.Project_Path }}
          -c Release
          -r win-x64
          --self-contained true
          -p:PublishSingleFile=true
          -p:IncludeAllContentForSelfExtract=true
          -p:PublishTrimmed=false
          -o publish

      - name: List published files
        run: dir publish

      - name: Create release folder
        run: New-Item -ItemType Directory -Path release -Force

      - name: Copy EXE to release folder
        run: |
          Get-ChildItem -Path "publish" -Filter "*.exe" | ForEach-Object {
            Copy-Item $_.FullName -Destination "release\$($_.Name)"
          }

      - name: Upload build output (optional for trace/debug)
        uses: actions/upload-artifact@v4
        with:
          name: Release-Build
          path: release

      - name: Create GitHub Release with EXE
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: release/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
